version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: reg_cms
      DATABASE_HOST: 145.38.197.14
      DATABASE_PORT: 5432
      DATABASE_USERNAME: website
      DATABASE_PASSWORD: website
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
